# Generated by Django 3.1.2 on 2020-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100, verbose_name='line1')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('zipcode', models.CharField(max_length=5, verbose_name='zipcode')),
            ],
        ),
    ]
