# Generated by Django 3.1.2 on 2020-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='line2'),
        ),
    ]
