version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    command: yarn start
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    ports:
      - '3000:3000'
